# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x06verify\"-\n\x04\x42ook\x12\x0e\n\x06\x62ookId\x18\x01 \x01(\t\x12\x15\n\rbook_quantity\x18\x02 \x01(\t\"\xb0\x02\n\x1eTransactionVerificationRequest\x12 \n\nuser_books\x18\x01 \x03(\x0b\x32\x0c.verify.Book\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x12\n\nuser_email\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x04 \x01(\t\x12\x13\n\x0b\x63\x61rd_expiry\x18\x05 \x01(\t\x12\x10\n\x08\x63\x61rd_cvv\x18\x06 \x01(\t\x12\x16\n\x0e\x62illing_street\x18\x07 \x01(\t\x12\x14\n\x0c\x62illing_city\x18\x08 \x01(\t\x12\x15\n\rbilling_state\x18\t \x01(\t\x12\x13\n\x0b\x62illing_zip\x18\n \x01(\t\x12\x17\n\x0fshipping_method\x18\x0b \x01(\t\x12\x16\n\x0eterms_accepted\x18\x0c \x01(\x08\"C\n\x1fTransactionVerificationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\x8c\x01\n\x1eTransactionVerificationService\x12j\n\x17TransactionVerification\x12&.verify.TransactionVerificationRequest\x1a\'.verify.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=42
  _globals['_BOOK']._serialized_end=87
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_start=90
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_end=394
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=396
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=463
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=466
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
